### ISSUE TITLE
ERROR ~ No such variable: ch_library

### ISSUE THREAD

**Issue by zhouzhendiao** [nf-core/crisprseq#61]
### Description of the bug

command:
```
nextflow run /path-to/nf-core-crisprseq-2.0.0/workflow \
    -preview \
    --analysis screening \
    --genome GRCh37 \
    -profile singularity \
    --igenomes_base /path-to/references \
    -offline \
    --outdir . \
    --input samplesheet.csv \
    -resume \
    --max_cpus 16 \
    --max_memory 64.GB \
    --max_time 256.h
```

samplesheet.csv
```
sample,fastq_1,fastq_2,condition
KO14,KO14_S1_L003_R1_001.fastq.gz,KO14_S1_L003_R2_001.fastq.gz,treatment
KO-control,KO_control_S6_L005_R1_001.fastq.gz,KO-control_S6_L005_R2_001.fastq.gz,control
```

output:
```
!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/crisprseq for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.7598497

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/crisprseq/blob/master/CITATIONS.md
------------------------------------------------------
[-        ] process > NFCORE_CRISPRSEQ:CRISPRSEQ_SCREENING:INPUT_CHECK_... -
ERROR ~ No such variable: ch_library

 -- Check script '/path-to/nf-core-crisprseq-2.0.0/workflow/./workflows/crisprseq_screening.nf' at line: 108 or see '.nextflow.log' file for more details
```

crisprseq_screening.nf at line: 108
```
105         //
106         // MODULE: Run mageck count
107         //
108         MAGECK_COUNT (
109             joined,
110             ch_library
111         )
112
113         ch_versions = ch_versions.mix(MAGECK_COUNT.out.versions.first())
114
115
116         MAGECK_COUNT.out.count.map {
117         it -> it[1]
118         }.set { ch_counts }
119
120     } else {
121         Channel.fromPath(params.count_table)
122         .set { ch_counts }
123     }
```

.nextflow.log
```
Jul-29 22:10:07.018 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_single` matches labels `process_single` for process with name NFCORE_CRISPRSEQ:CRISPRSEQ_SCREENING:INPUT_CHECK_SCREENING:SAMPLESHEET_CHECK_SCREENING
Jul-29 22:10:07.027 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Jul-29 22:10:07.027 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Jul-29 22:10:07.034 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Jul-29 22:10:07.040 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=56; memory=251.6 GB; capacity=56; pollInterval=100ms; dumpInterval=5m
Jul-29 22:10:07.212 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches labels `process_medium` for process with name NFCORE_CRISPRSEQ:CRISPRSEQ_SCREENING:FASTQC
Jul-29 22:10:07.213 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:FASTQC` matches process NFCORE_CRISPRSEQ:CRISPRSEQ_SCREENING:FASTQC
Jul-29 22:10:07.216 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Jul-29 22:10:07.217 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Jul-29 22:10:07.247 [main] DEBUG nextflow.Session - Session aborted -- Cause: No such property: ch_library for class: nextflow.script.WorkflowBinding
Jul-29 22:10:07.266 [main] DEBUG nextflow.Session - The following nodes are still active:
  [operator] splitCsv
  [operator] map
  [operator] mix
  [operator] mix
  [operator] map
  [operator] reduce
  [operator] map

Jul-29 22:10:07.274 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: No such property: ch_library for class: nextflow.script.WorkflowBinding
        at groovy.lang.Binding.getVariable(Binding.java:61)
        at nextflow.script.WorkflowBinding.getVariable(WorkflowBinding.groovy:140)
        at groovy.lang.Binding.getProperty(Binding.java:116)
        at nextflow.script.WorkflowBinding.getProperty(WorkflowBinding.groovy:129)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
        at groovy.lang.Closure.getPropertyTryThese(Closure.java:320)
        at groovy.lang.Closure.getPropertyDelegateFirst(Closure.java:310)
        at groovy.lang.Closure.getProperty(Closure.java:296)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
        at Script_21dbb60c$_runScript_closure2$_closure4.doCall(Script_21dbb60c:108)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:204)
        at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:188)
        at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
        at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
        at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:102)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:408)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:350)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at Script_54323686$_runScript_closure1$_closure3.doCall(Script_54323686:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:204)
        at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:188)
        at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
        at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
        at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:102)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:408)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:350)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at Script_54323686$_runScript_closure2$_closure4.doCall(Script_54323686:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:204)
        at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:188)
        at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
        at nextflow.script.IterableDef$invoke_a.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at nextflow.script.BaseScript.run0(BaseScript.groovy:183)
        at nextflow.script.BaseScript.run(BaseScript.groovy:192)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:229)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:224)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:130)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:368)
        at nextflow.cli.Launcher.run(Launcher.groovy:494)
        at nextflow.cli.Launcher.main(Launcher.groovy:653)
```

**Comment by zhouzhendiao** [comment]
OK， the issue above is because of lacking `--library library.csv`. But tutorial in [screening](https://nf-co.re/crisprseq/2.0.0/docs/usage/screening) part seems have no description about library.csv. One can find in MAGeCK [document](https://sourceforge.net/p/mageck/wiki/usage/).

**Comment by LaurenceKuhl** [comment]
Hi @zhouzhendiao thanks a lot for reporting! :)
So just to be clear you got it running but what was lacking was the correct documentation? I'll add it.

**Comment by zhouzhendiao** [comment]
> Hi @zhouzhendiao thanks a lot for reporting! :) So just to be clear you got it running but what was lacking was the correct documentation? I'll add it.

Thanks for replying!

I'm using `screning` sub-pipeline, the paramters `--library library.csv` in the command but lacking of detailed description :

```
nextflow run nf-core/crisprseq --analysis screening --input samplesheet.csv --library library.csv --outdir <OUTDIR> -profile docker
```

Maybe the format of library.csv is described in MAGeCK. Sorry that I'm not familiar with it. Can you kindly add this?

**Comment by LaurenceKuhl** [comment]
Hi we added examples in the documentation, let me know if it's still not clear enough you can re open this :) thanks a lot!
